### ISSUE TITLE
Misconfiguration exposed risky data

### ISSUE THREAD

**Issue by conf-test** [Servarr/mediawiki-docker#1]
Hi,

I'm a security researcher and am doing some study of public docker images. I found some misconfigurations in your this image that may expose some risky data at runtime. The exposure I found include:

composer: /composer.lock
git: /extensions/OpenIDConnect/.gitignore
sql: /extensions/OpenIDConnect/sql/mysql/AddTable.sql
vendor: /extensions/MW-OAuth2Client/vendors/*
php internal error messages: extensions/MW-OAuth2Client/vendors/oauth2-client/vendor/phpunit/phpunit/tests/_files/DataProviderDebugTest.php

Those are all blocked in the official mediawiki docker image and here are some reference about these exposures:
https://stackoverflow.com/questions/11078572/should-i-use-phpunit-in-a-staging-production-environment
https://github.com/bolt/bolt/issues/375
https://github.com/wp-cli/doctor-command/issues/98

If you want, I can also help fix them. Please let me know what you think. Thanks!

Best,
~cf

**Comment by ta264** [comment]
A PR would be great! Thanks!
